version: '3.7'
services:
  postgres:
    image: postgres
    ports:   
      - "5432:5432" 
    environment:
      POSTGRES_DB: temtem-app
      POSTGRES_USER: temtem
      POSTGRES_PASSWORD: temtem
    volumes:
      - ./data:/var/lib/postgresql/data